# Generated by Django 2.0.5 on 2018-11-26 06:59

from django.db import migrations, models
import django_markdown.models
import mdeditor.fields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0012_remove_question_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('content', mdeditor.fields.MDTextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=django_markdown.models.MarkdownField(verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='出版日期'),
        ),
        migrations.AlterField(
            model_name='question',
            name='reward',
            field=models.IntegerField(default=0, verbose_name='奖金'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='多个标签之间使用逗号分割', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
    ]
